/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiKey {
  'id' : string,
  'status' : ApiKeyStatus,
  'lastUsedAt' : bigint,
  'expiresAt' : bigint,
  'scopes' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'createdById' : string,
  'keyHash' : string,
  'prefix' : string,
  'revokedById' : string,
}
export interface ApiKeyRevokeProposal {
  'id' : string,
  'keyName' : string,
  'keyId' : string,
  'proposedAt' : bigint,
  'proposerId' : string,
  'reason' : string,
}
export type ApiKeyStatus = { 'active' : null } |
  { 'revoked' : null };
export interface Contract {
  'id' : string,
  'status' : ContractStatus,
  'terms' : string,
  'title' : string,
  'orgId' : string,
  'templateId' : string,
  'approvedBy' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'contractType' : ContractType,
  'updatedAt' : bigint,
  'licenseId' : string,
  'financingOfferId' : string,
  'workId' : string,
  'proposedBy' : string,
  'parties' : Array<ContractParty>,
}
export interface ContractParty {
  'name' : string,
  'role' : string,
  'principalId' : string,
}
export type ContractStatus = { 'voided' : null } |
  { 'pendingApproval' : null } |
  { 'approved' : null } |
  { 'executed' : null } |
  { 'draft' : null };
export interface ContractTemplate {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'contractType' : ContractType,
  'bodyTemplate' : string,
}
export type ContractType = { 'custom' : null } |
  { 'financing' : null } |
  { 'license' : null };
export interface MarketplaceListing {
  'id' : string,
  'territory' : string,
  'status' : string,
  'rightsHolderPrincipal' : Principal,
  'askingPrice' : number,
  'createdAt' : bigint,
  'rightsHolderName' : string,
  'description' : string,
  'genre' : string,
  'licenseType' : string,
  'currency' : string,
  'workId' : string,
  'workTitle' : string,
}
export interface MemberProfile {
  'bio' : string,
  'country' : string,
  'displayName' : string,
  'orgIds' : Array<string>,
  'createdAt' : bigint,
  'languages' : Array<string>,
  'website' : string,
  'updatedAt' : bigint,
  'principalId' : string,
}
export interface PlatformFeeConfig {
  'pendingRoyaltyProcessingFeeBps' : bigint,
  'licenseFeeBps' : bigint,
  'pendingLicenseFeeBps' : bigint,
  'pendingFinancingPlatformFeeBps' : bigint,
  'lastUpdatedAt' : bigint,
  'lastUpdatedBy' : string,
  'royaltyProcessingFeeBps' : bigint,
  'proposedAt' : bigint,
  'proposedBy' : string,
  'financingPlatformFeeBps' : bigint,
}
export interface PlatformHealthMetrics {
  'totalRevenueSourcesCents' : bigint,
  'activeLicenses' : bigint,
  'totalOrgs' : bigint,
  'openDisputes' : bigint,
  'totalPayoutsProcessed' : bigint,
  'totalContractsExecuted' : bigint,
  'totalMembers' : bigint,
  'totalWorks' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WebhookDeliveryLog {
  'id' : string,
  'responsePreview' : string,
  'webhookId' : string,
  'event' : string,
  'timestamp' : bigint,
  'statusCode' : bigint,
  'success' : boolean,
}
export interface WebhookEndpoint {
  'id' : string,
  'url' : string,
  'active' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'createdById' : string,
  'secret' : string,
  'events' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveContractExecution' : ActorMethod<[string], [] | [Contract]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRevokeProposal' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'confirmFeeChange' : ActorMethod<[], PlatformFeeConfig>,
  'confirmRevokeApiKey' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createContract' : ActorMethod<
    [
      string,
      ContractType,
      string,
      string,
      Array<ContractParty>,
      string,
      string,
      string,
      string,
    ],
    Contract
  >,
  'createContractTemplate' : ActorMethod<
    [string, ContractType, string],
    ContractTemplate
  >,
  'createListing' : ActorMethod<
    [string, string, string, string, string, number, string, string, string],
    { 'ok' : MarketplaceListing } |
      { 'err' : string }
  >,
  'deleteWebhook' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'generateApiKey' : ActorMethod<
    [string, Array<string>, bigint],
    { 'key' : string, 'metadata' : ApiKey }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContractById' : ActorMethod<[string], [] | [Contract]>,
  'getContractsByOrg' : ActorMethod<[string], Array<Contract>>,
  'getMarketplaceListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getMyListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getPlatformFeeConfig' : ActorMethod<[], PlatformFeeConfig>,
  'getPlatformHealthMetrics' : ActorMethod<[], PlatformHealthMetrics>,
  'getTemplateById' : ActorMethod<[string], [] | [ContractTemplate]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllContracts' : ActorMethod<[], Array<Contract>>,
  'listAllProfiles' : ActorMethod<[], Array<MemberProfile>>,
  'listApiKeys' : ActorMethod<[], Array<ApiKey>>,
  'listContractTemplates' : ActorMethod<[], Array<ContractTemplate>>,
  'listRevokeProposals' : ActorMethod<[], Array<ApiKeyRevokeProposal>>,
  'listWebhookLogs' : ActorMethod<[], Array<WebhookDeliveryLog>>,
  'listWebhooks' : ActorMethod<[], Array<WebhookEndpoint>>,
  'lookupByISRC' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'lookupByISWC' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'pingWebhook' : ActorMethod<
    [string],
    { 'ok' : WebhookDeliveryLog } |
      { 'err' : string }
  >,
  'proposeContractExecution' : ActorMethod<[string], [] | [Contract]>,
  'proposeFeeChange' : ActorMethod<[bigint, bigint, bigint], PlatformFeeConfig>,
  'proposeRevokeApiKey' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'registerWebhook' : ActorMethod<
    [string, string, Array<string>],
    { 'ok' : WebhookEndpoint } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateContractTerms' : ActorMethod<[string, string], [] | [Contract]>,
  'updateListingStatus' : ActorMethod<
    [string, string],
    { 'ok' : MarketplaceListing } |
      { 'err' : string }
  >,
  'updateWebhookStatus' : ActorMethod<
    [string, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'voidContract' : ActorMethod<[string], [] | [Contract]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];