/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContractStatus = IDL.Variant({
  'voided' : IDL.Null,
  'pendingApproval' : IDL.Null,
  'approved' : IDL.Null,
  'executed' : IDL.Null,
  'draft' : IDL.Null,
});
export const ContractType = IDL.Variant({
  'custom' : IDL.Null,
  'financing' : IDL.Null,
  'license' : IDL.Null,
});
export const ContractParty = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'principalId' : IDL.Text,
});
export const Contract = IDL.Record({
  'id' : IDL.Text,
  'status' : ContractStatus,
  'terms' : IDL.Text,
  'title' : IDL.Text,
  'orgId' : IDL.Text,
  'templateId' : IDL.Text,
  'approvedBy' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'contractType' : ContractType,
  'updatedAt' : IDL.Int,
  'licenseId' : IDL.Text,
  'financingOfferId' : IDL.Text,
  'workId' : IDL.Text,
  'proposedBy' : IDL.Text,
  'parties' : IDL.Vec(ContractParty),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlatformFeeConfig = IDL.Record({
  'pendingRoyaltyProcessingFeeBps' : IDL.Nat,
  'licenseFeeBps' : IDL.Nat,
  'pendingLicenseFeeBps' : IDL.Nat,
  'pendingFinancingPlatformFeeBps' : IDL.Nat,
  'lastUpdatedAt' : IDL.Int,
  'lastUpdatedBy' : IDL.Text,
  'royaltyProcessingFeeBps' : IDL.Nat,
  'proposedAt' : IDL.Int,
  'proposedBy' : IDL.Text,
  'financingPlatformFeeBps' : IDL.Nat,
});
export const ContractTemplate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'contractType' : ContractType,
  'bodyTemplate' : IDL.Text,
});
export const MarketplaceListing = IDL.Record({
  'id' : IDL.Text,
  'territory' : IDL.Text,
  'status' : IDL.Text,
  'rightsHolderPrincipal' : IDL.Principal,
  'askingPrice' : IDL.Float64,
  'createdAt' : IDL.Int,
  'rightsHolderName' : IDL.Text,
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'licenseType' : IDL.Text,
  'currency' : IDL.Text,
  'workId' : IDL.Text,
  'workTitle' : IDL.Text,
});
export const ApiKeyStatus = IDL.Variant({
  'active' : IDL.Null,
  'revoked' : IDL.Null,
});
export const ApiKey = IDL.Record({
  'id' : IDL.Text,
  'status' : ApiKeyStatus,
  'lastUsedAt' : IDL.Int,
  'expiresAt' : IDL.Int,
  'scopes' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdById' : IDL.Text,
  'keyHash' : IDL.Text,
  'prefix' : IDL.Text,
  'revokedById' : IDL.Text,
});
export const PlatformHealthMetrics = IDL.Record({
  'totalRevenueSourcesCents' : IDL.Nat,
  'activeLicenses' : IDL.Nat,
  'totalOrgs' : IDL.Nat,
  'openDisputes' : IDL.Nat,
  'totalPayoutsProcessed' : IDL.Nat,
  'totalContractsExecuted' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'totalWorks' : IDL.Nat,
});
export const MemberProfile = IDL.Record({
  'bio' : IDL.Text,
  'country' : IDL.Text,
  'displayName' : IDL.Text,
  'orgIds' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'languages' : IDL.Vec(IDL.Text),
  'website' : IDL.Text,
  'updatedAt' : IDL.Int,
  'principalId' : IDL.Text,
});
export const ApiKeyRevokeProposal = IDL.Record({
  'id' : IDL.Text,
  'keyName' : IDL.Text,
  'keyId' : IDL.Text,
  'proposedAt' : IDL.Int,
  'proposerId' : IDL.Text,
  'reason' : IDL.Text,
});
export const WebhookDeliveryLog = IDL.Record({
  'id' : IDL.Text,
  'responsePreview' : IDL.Text,
  'webhookId' : IDL.Text,
  'event' : IDL.Text,
  'timestamp' : IDL.Int,
  'statusCode' : IDL.Nat,
  'success' : IDL.Bool,
});
export const WebhookEndpoint = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdById' : IDL.Text,
  'secret' : IDL.Text,
  'events' : IDL.Vec(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveContractExecution' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRevokeProposal' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'confirmFeeChange' : IDL.Func([], [PlatformFeeConfig], []),
  'confirmRevokeApiKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createContract' : IDL.Func(
      [
        IDL.Text,
        ContractType,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ContractParty),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Contract],
      [],
    ),
  'createContractTemplate' : IDL.Func(
      [IDL.Text, ContractType, IDL.Text],
      [ContractTemplate],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Variant({ 'ok' : MarketplaceListing, 'err' : IDL.Text })],
      [],
    ),
  'deleteWebhook' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateApiKey' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Record({ 'key' : IDL.Text, 'metadata' : ApiKey })],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContractById' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], ['query']),
  'getContractsByOrg' : IDL.Func([IDL.Text], [IDL.Vec(Contract)], ['query']),
  'getMarketplaceListings' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'getMyListings' : IDL.Func([], [IDL.Vec(MarketplaceListing)], ['query']),
  'getPlatformFeeConfig' : IDL.Func([], [PlatformFeeConfig], ['query']),
  'getPlatformHealthMetrics' : IDL.Func([], [PlatformHealthMetrics], ['query']),
  'getTemplateById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContractTemplate)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
  'listAllProfiles' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
  'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
  'listContractTemplates' : IDL.Func(
      [],
      [IDL.Vec(ContractTemplate)],
      ['query'],
    ),
  'listRevokeProposals' : IDL.Func(
      [],
      [IDL.Vec(ApiKeyRevokeProposal)],
      ['query'],
    ),
  'listWebhookLogs' : IDL.Func([], [IDL.Vec(WebhookDeliveryLog)], ['query']),
  'listWebhooks' : IDL.Func([], [IDL.Vec(WebhookEndpoint)], ['query']),
  'lookupByISRC' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'lookupByISWC' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'pingWebhook' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : WebhookDeliveryLog, 'err' : IDL.Text })],
      [],
    ),
  'proposeContractExecution' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], []),
  'proposeFeeChange' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [PlatformFeeConfig],
      [],
    ),
  'proposeRevokeApiKey' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'registerWebhook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'ok' : WebhookEndpoint, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateContractTerms' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Contract)],
      [],
    ),
  'updateListingStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : MarketplaceListing, 'err' : IDL.Text })],
      [],
    ),
  'updateWebhookStatus' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'voidContract' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContractStatus = IDL.Variant({
    'voided' : IDL.Null,
    'pendingApproval' : IDL.Null,
    'approved' : IDL.Null,
    'executed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ContractType = IDL.Variant({
    'custom' : IDL.Null,
    'financing' : IDL.Null,
    'license' : IDL.Null,
  });
  const ContractParty = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const Contract = IDL.Record({
    'id' : IDL.Text,
    'status' : ContractStatus,
    'terms' : IDL.Text,
    'title' : IDL.Text,
    'orgId' : IDL.Text,
    'templateId' : IDL.Text,
    'approvedBy' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'contractType' : ContractType,
    'updatedAt' : IDL.Int,
    'licenseId' : IDL.Text,
    'financingOfferId' : IDL.Text,
    'workId' : IDL.Text,
    'proposedBy' : IDL.Text,
    'parties' : IDL.Vec(ContractParty),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlatformFeeConfig = IDL.Record({
    'pendingRoyaltyProcessingFeeBps' : IDL.Nat,
    'licenseFeeBps' : IDL.Nat,
    'pendingLicenseFeeBps' : IDL.Nat,
    'pendingFinancingPlatformFeeBps' : IDL.Nat,
    'lastUpdatedAt' : IDL.Int,
    'lastUpdatedBy' : IDL.Text,
    'royaltyProcessingFeeBps' : IDL.Nat,
    'proposedAt' : IDL.Int,
    'proposedBy' : IDL.Text,
    'financingPlatformFeeBps' : IDL.Nat,
  });
  const ContractTemplate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'contractType' : ContractType,
    'bodyTemplate' : IDL.Text,
  });
  const MarketplaceListing = IDL.Record({
    'id' : IDL.Text,
    'territory' : IDL.Text,
    'status' : IDL.Text,
    'rightsHolderPrincipal' : IDL.Principal,
    'askingPrice' : IDL.Float64,
    'createdAt' : IDL.Int,
    'rightsHolderName' : IDL.Text,
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'licenseType' : IDL.Text,
    'currency' : IDL.Text,
    'workId' : IDL.Text,
    'workTitle' : IDL.Text,
  });
  const ApiKeyStatus = IDL.Variant({
    'active' : IDL.Null,
    'revoked' : IDL.Null,
  });
  const ApiKey = IDL.Record({
    'id' : IDL.Text,
    'status' : ApiKeyStatus,
    'lastUsedAt' : IDL.Int,
    'expiresAt' : IDL.Int,
    'scopes' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdById' : IDL.Text,
    'keyHash' : IDL.Text,
    'prefix' : IDL.Text,
    'revokedById' : IDL.Text,
  });
  const PlatformHealthMetrics = IDL.Record({
    'totalRevenueSourcesCents' : IDL.Nat,
    'activeLicenses' : IDL.Nat,
    'totalOrgs' : IDL.Nat,
    'openDisputes' : IDL.Nat,
    'totalPayoutsProcessed' : IDL.Nat,
    'totalContractsExecuted' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'totalWorks' : IDL.Nat,
  });
  const MemberProfile = IDL.Record({
    'bio' : IDL.Text,
    'country' : IDL.Text,
    'displayName' : IDL.Text,
    'orgIds' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'languages' : IDL.Vec(IDL.Text),
    'website' : IDL.Text,
    'updatedAt' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const ApiKeyRevokeProposal = IDL.Record({
    'id' : IDL.Text,
    'keyName' : IDL.Text,
    'keyId' : IDL.Text,
    'proposedAt' : IDL.Int,
    'proposerId' : IDL.Text,
    'reason' : IDL.Text,
  });
  const WebhookDeliveryLog = IDL.Record({
    'id' : IDL.Text,
    'responsePreview' : IDL.Text,
    'webhookId' : IDL.Text,
    'event' : IDL.Text,
    'timestamp' : IDL.Int,
    'statusCode' : IDL.Nat,
    'success' : IDL.Bool,
  });
  const WebhookEndpoint = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdById' : IDL.Text,
    'secret' : IDL.Text,
    'events' : IDL.Vec(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveContractExecution' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRevokeProposal' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'confirmFeeChange' : IDL.Func([], [PlatformFeeConfig], []),
    'confirmRevokeApiKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createContract' : IDL.Func(
        [
          IDL.Text,
          ContractType,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ContractParty),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Contract],
        [],
      ),
    'createContractTemplate' : IDL.Func(
        [IDL.Text, ContractType, IDL.Text],
        [ContractTemplate],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Variant({ 'ok' : MarketplaceListing, 'err' : IDL.Text })],
        [],
      ),
    'deleteWebhook' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateApiKey' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Record({ 'key' : IDL.Text, 'metadata' : ApiKey })],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContractById' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], ['query']),
    'getContractsByOrg' : IDL.Func([IDL.Text], [IDL.Vec(Contract)], ['query']),
    'getMarketplaceListings' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'getMyListings' : IDL.Func([], [IDL.Vec(MarketplaceListing)], ['query']),
    'getPlatformFeeConfig' : IDL.Func([], [PlatformFeeConfig], ['query']),
    'getPlatformHealthMetrics' : IDL.Func(
        [],
        [PlatformHealthMetrics],
        ['query'],
      ),
    'getTemplateById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContractTemplate)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllContracts' : IDL.Func([], [IDL.Vec(Contract)], ['query']),
    'listAllProfiles' : IDL.Func([], [IDL.Vec(MemberProfile)], ['query']),
    'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKey)], ['query']),
    'listContractTemplates' : IDL.Func(
        [],
        [IDL.Vec(ContractTemplate)],
        ['query'],
      ),
    'listRevokeProposals' : IDL.Func(
        [],
        [IDL.Vec(ApiKeyRevokeProposal)],
        ['query'],
      ),
    'listWebhookLogs' : IDL.Func([], [IDL.Vec(WebhookDeliveryLog)], ['query']),
    'listWebhooks' : IDL.Func([], [IDL.Vec(WebhookEndpoint)], ['query']),
    'lookupByISRC' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'lookupByISWC' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'pingWebhook' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : WebhookDeliveryLog, 'err' : IDL.Text })],
        [],
      ),
    'proposeContractExecution' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], []),
    'proposeFeeChange' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [PlatformFeeConfig],
        [],
      ),
    'proposeRevokeApiKey' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'registerWebhook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'ok' : WebhookEndpoint, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateContractTerms' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Contract)],
        [],
      ),
    'updateListingStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : MarketplaceListing, 'err' : IDL.Text })],
        [],
      ),
    'updateWebhookStatus' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'voidContract' : IDL.Func([IDL.Text], [IDL.Opt(Contract)], []),
  });
};

export const init = ({ IDL }) => { return []; };