/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface WebhookEndpoint {
    id: string;
    url: string;
    active: boolean;
    name: string;
    createdAt: bigint;
    createdById: string;
    secret: string;
    events: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ContractTemplate {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    contractType: ContractType;
    bodyTemplate: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface PlatformHealthMetrics {
    totalRevenueSourcesCents: bigint;
    activeLicenses: bigint;
    totalOrgs: bigint;
    openDisputes: bigint;
    totalPayoutsProcessed: bigint;
    totalContractsExecuted: bigint;
    totalMembers: bigint;
    totalWorks: bigint;
}
export interface MemberProfile {
    bio: string;
    country: string;
    displayName: string;
    orgIds: Array<string>;
    createdAt: bigint;
    languages: Array<string>;
    website: string;
    updatedAt: bigint;
    principalId: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PlatformFeeConfig {
    pendingRoyaltyProcessingFeeBps: bigint;
    licenseFeeBps: bigint;
    pendingLicenseFeeBps: bigint;
    pendingFinancingPlatformFeeBps: bigint;
    lastUpdatedAt: bigint;
    lastUpdatedBy: string;
    royaltyProcessingFeeBps: bigint;
    proposedAt: bigint;
    proposedBy: string;
    financingPlatformFeeBps: bigint;
}
export interface MarketplaceListing {
    id: string;
    territory: string;
    status: string;
    rightsHolderPrincipal: Principal;
    askingPrice: number;
    createdAt: bigint;
    rightsHolderName: string;
    description: string;
    genre: string;
    licenseType: string;
    currency: string;
    workId: string;
    workTitle: string;
}
export interface ApiKey {
    id: string;
    status: ApiKeyStatus;
    lastUsedAt: bigint;
    expiresAt: bigint;
    scopes: Array<string>;
    name: string;
    createdAt: bigint;
    createdById: string;
    keyHash: string;
    prefix: string;
    revokedById: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ApiKeyRevokeProposal {
    id: string;
    keyName: string;
    keyId: string;
    proposedAt: bigint;
    proposerId: string;
    reason: string;
}
export interface WebhookDeliveryLog {
    id: string;
    responsePreview: string;
    webhookId: string;
    event: string;
    timestamp: bigint;
    statusCode: bigint;
    success: boolean;
}
export interface ContractParty {
    name: string;
    role: string;
    principalId: string;
}
export interface Contract {
    id: string;
    status: ContractStatus;
    terms: string;
    title: string;
    orgId: string;
    templateId: string;
    approvedBy: string;
    createdAt: bigint;
    createdBy: string;
    contractType: ContractType;
    updatedAt: bigint;
    licenseId: string;
    financingOfferId: string;
    workId: string;
    proposedBy: string;
    parties: Array<ContractParty>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApiKeyStatus {
    active = "active",
    revoked = "revoked"
}
export enum ContractStatus {
    voided = "voided",
    pendingApproval = "pendingApproval",
    approved = "approved",
    executed = "executed",
    draft = "draft"
}
export enum ContractType {
    custom = "custom",
    financing = "financing",
    license = "license"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveContractExecution(id: string): Promise<Contract | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelRevokeProposal(proposalId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    confirmFeeChange(): Promise<PlatformFeeConfig>;
    confirmRevokeApiKey(proposalId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createContract(orgId: string, contractType: ContractType, templateId: string, title: string, parties: Array<ContractParty>, workId: string, licenseId: string, financingOfferId: string, terms: string): Promise<Contract>;
    createContractTemplate(name: string, contractType: ContractType, bodyTemplate: string): Promise<ContractTemplate>;
    createListing(workId: string, workTitle: string, rightsHolderName: string, licenseType: string, territory: string, askingPrice: number, currency: string, description: string, genre: string): Promise<{
        __kind__: "ok";
        ok: MarketplaceListing;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteWebhook(id: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    generateApiKey(name: string, scopes: Array<string>, expiresInDays: bigint): Promise<{
        key: string;
        metadata: ApiKey;
    }>;
    getCallerUserRole(): Promise<UserRole>;
    getContractById(id: string): Promise<Contract | null>;
    getContractsByOrg(orgId: string): Promise<Array<Contract>>;
    getMarketplaceListings(): Promise<Array<MarketplaceListing>>;
    getMyListings(): Promise<Array<MarketplaceListing>>;
    getPlatformFeeConfig(): Promise<PlatformFeeConfig>;
    getPlatformHealthMetrics(): Promise<PlatformHealthMetrics>;
    getTemplateById(id: string): Promise<ContractTemplate | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllContracts(): Promise<Array<Contract>>;
    listAllProfiles(): Promise<Array<MemberProfile>>;
    listApiKeys(): Promise<Array<ApiKey>>;
    listContractTemplates(): Promise<Array<ContractTemplate>>;
    listRevokeProposals(): Promise<Array<ApiKeyRevokeProposal>>;
    listWebhookLogs(): Promise<Array<WebhookDeliveryLog>>;
    listWebhooks(): Promise<Array<WebhookEndpoint>>;
    lookupByISRC(isrc: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    lookupByISWC(iswc: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    pingWebhook(id: string): Promise<{
        __kind__: "ok";
        ok: WebhookDeliveryLog;
    } | {
        __kind__: "err";
        err: string;
    }>;
    proposeContractExecution(id: string): Promise<Contract | null>;
    proposeFeeChange(royaltyProcessingFeeBps: bigint, licenseFeeBps: bigint, financingPlatformFeeBps: bigint): Promise<PlatformFeeConfig>;
    proposeRevokeApiKey(keyId: string, reason: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerWebhook(name: string, url: string, events: Array<string>): Promise<{
        __kind__: "ok";
        ok: WebhookEndpoint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateContractTerms(id: string, terms: string): Promise<Contract | null>;
    updateListingStatus(id: string, status: string): Promise<{
        __kind__: "ok";
        ok: MarketplaceListing;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateWebhookStatus(id: string, active: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    voidContract(id: string): Promise<Contract | null>;
}
import type { ApiKey as _ApiKey, ApiKeyStatus as _ApiKeyStatus, Contract as _Contract, ContractParty as _ContractParty, ContractStatus as _ContractStatus, ContractTemplate as _ContractTemplate, ContractType as _ContractType, MarketplaceListing as _MarketplaceListing, UserRole as _UserRole, WebhookDeliveryLog as _WebhookDeliveryLog, WebhookEndpoint as _WebhookEndpoint, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveContractExecution(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.approveContractExecution(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveContractExecution(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelRevokeProposal(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRevokeProposal(arg0);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRevokeProposal(arg0);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmFeeChange(): Promise<PlatformFeeConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmFeeChange();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmFeeChange();
            return result;
        }
    }
    async confirmRevokeApiKey(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmRevokeApiKey(arg0);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmRevokeApiKey(arg0);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createContract(arg0: string, arg1: ContractType, arg2: string, arg3: string, arg4: Array<ContractParty>, arg5: string, arg6: string, arg7: string, arg8: string): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.createContract(arg0, to_candid_ContractType_n18(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_Contract_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContract(arg0, to_candid_ContractType_n18(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_Contract_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createContractTemplate(arg0: string, arg1: ContractType, arg2: string): Promise<ContractTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.createContractTemplate(arg0, to_candid_ContractType_n18(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_ContractTemplate_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContractTemplate(arg0, to_candid_ContractType_n18(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_ContractTemplate_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number, arg6: string, arg7: string, arg8: string): Promise<{
        __kind__: "ok";
        ok: MarketplaceListing;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteWebhook(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWebhook(arg0);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWebhook(arg0);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateApiKey(arg0: string, arg1: Array<string>, arg2: bigint): Promise<{
        key: string;
        metadata: ApiKey;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiKey(arg0, arg1, arg2);
                return from_candid_record_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiKey(arg0, arg1, arg2);
            return from_candid_record_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractById(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractById(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractById(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractsByOrg(arg0: string): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractsByOrg(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractsByOrg(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketplaceListings(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListings();
            return result;
        }
    }
    async getMyListings(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return result;
        }
    }
    async getPlatformFeeConfig(): Promise<PlatformFeeConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformFeeConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformFeeConfig();
            return result;
        }
    }
    async getPlatformHealthMetrics(): Promise<PlatformHealthMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformHealthMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformHealthMetrics();
            return result;
        }
    }
    async getTemplateById(arg0: string): Promise<ContractTemplate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplateById(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplateById(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllContracts(): Promise<Array<Contract>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllContracts();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllContracts();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllProfiles(): Promise<Array<MemberProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllProfiles();
            return result;
        }
    }
    async listApiKeys(): Promise<Array<ApiKey>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApiKeys();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApiKeys();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async listContractTemplates(): Promise<Array<ContractTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContractTemplates();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContractTemplates();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRevokeProposals(): Promise<Array<ApiKeyRevokeProposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRevokeProposals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRevokeProposals();
            return result;
        }
    }
    async listWebhookLogs(): Promise<Array<WebhookDeliveryLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWebhookLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWebhookLogs();
            return result;
        }
    }
    async listWebhooks(): Promise<Array<WebhookEndpoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWebhooks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWebhooks();
            return result;
        }
    }
    async lookupByISRC(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupByISRC(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupByISRC(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async lookupByISWC(arg0: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupByISWC(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupByISWC(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async pingWebhook(arg0: string): Promise<{
        __kind__: "ok";
        ok: WebhookDeliveryLog;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.pingWebhook(arg0);
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pingWebhook(arg0);
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async proposeContractExecution(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.proposeContractExecution(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proposeContractExecution(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async proposeFeeChange(arg0: bigint, arg1: bigint, arg2: bigint): Promise<PlatformFeeConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.proposeFeeChange(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proposeFeeChange(arg0, arg1, arg2);
            return result;
        }
    }
    async proposeRevokeApiKey(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.proposeRevokeApiKey(arg0, arg1);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proposeRevokeApiKey(arg0, arg1);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWebhook(arg0: string, arg1: string, arg2: Array<string>): Promise<{
        __kind__: "ok";
        ok: WebhookEndpoint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWebhook(arg0, arg1, arg2);
                return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWebhook(arg0, arg1, arg2);
            return from_candid_variant_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateContractTerms(arg0: string, arg1: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContractTerms(arg0, arg1);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContractTerms(arg0, arg1);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateListingStatus(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: MarketplaceListing;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingStatus(arg0, arg1);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingStatus(arg0, arg1);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateWebhookStatus(arg0: string, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebhookStatus(arg0, arg1);
                return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebhookStatus(arg0, arg1);
            return from_candid_variant_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async voidContract(arg0: string): Promise<Contract | null> {
        if (this.processError) {
            try {
                const result = await this.actor.voidContract(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voidContract(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApiKeyStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKeyStatus): ApiKeyStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ApiKey_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKey): ApiKey {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ContractStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractStatus): ContractStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ContractTemplate_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractTemplate): ContractTemplate {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ContractType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractType): ContractType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContractTemplate]): ContractTemplate | null {
    return value.length === 0 ? null : from_candid_ContractTemplate_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contract]): Contract | null {
    return value.length === 0 ? null : from_candid_Contract_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ContractStatus;
    terms: string;
    title: string;
    orgId: string;
    templateId: string;
    approvedBy: string;
    createdAt: bigint;
    createdBy: string;
    contractType: _ContractType;
    updatedAt: bigint;
    licenseId: string;
    financingOfferId: string;
    workId: string;
    proposedBy: string;
    parties: Array<_ContractParty>;
}): {
    id: string;
    status: ContractStatus;
    terms: string;
    title: string;
    orgId: string;
    templateId: string;
    approvedBy: string;
    createdAt: bigint;
    createdBy: string;
    contractType: ContractType;
    updatedAt: bigint;
    licenseId: string;
    financingOfferId: string;
    workId: string;
    proposedBy: string;
    parties: Array<ContractParty>;
} {
    return {
        id: value.id,
        status: from_candid_ContractStatus_n11(_uploadFile, _downloadFile, value.status),
        terms: value.terms,
        title: value.title,
        orgId: value.orgId,
        templateId: value.templateId,
        approvedBy: value.approvedBy,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        contractType: from_candid_ContractType_n13(_uploadFile, _downloadFile, value.contractType),
        updatedAt: value.updatedAt,
        licenseId: value.licenseId,
        financingOfferId: value.financingOfferId,
        workId: value.workId,
        proposedBy: value.proposedBy,
        parties: value.parties
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    contractType: _ContractType;
    bodyTemplate: string;
}): {
    id: string;
    name: string;
    createdAt: bigint;
    createdBy: string;
    contractType: ContractType;
    bodyTemplate: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        contractType: from_candid_ContractType_n13(_uploadFile, _downloadFile, value.contractType),
        bodyTemplate: value.bodyTemplate
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    key: string;
    metadata: _ApiKey;
}): {
    key: string;
    metadata: ApiKey;
} {
    return {
        key: value.key,
        metadata: from_candid_ApiKey_n24(_uploadFile, _downloadFile, value.metadata)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ApiKeyStatus;
    lastUsedAt: bigint;
    expiresAt: bigint;
    scopes: Array<string>;
    name: string;
    createdAt: bigint;
    createdById: string;
    keyHash: string;
    prefix: string;
    revokedById: string;
}): {
    id: string;
    status: ApiKeyStatus;
    lastUsedAt: bigint;
    expiresAt: bigint;
    scopes: Array<string>;
    name: string;
    createdAt: bigint;
    createdById: string;
    keyHash: string;
    prefix: string;
    revokedById: string;
} {
    return {
        id: value.id,
        status: from_candid_ApiKeyStatus_n26(_uploadFile, _downloadFile, value.status),
        lastUsedAt: value.lastUsedAt,
        expiresAt: value.expiresAt,
        scopes: value.scopes,
        name: value.name,
        createdAt: value.createdAt,
        createdById: value.createdById,
        keyHash: value.keyHash,
        prefix: value.prefix,
        revokedById: value.revokedById
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    voided: null;
} | {
    pendingApproval: null;
} | {
    approved: null;
} | {
    executed: null;
} | {
    draft: null;
}): ContractStatus {
    return "voided" in value ? ContractStatus.voided : "pendingApproval" in value ? ContractStatus.pendingApproval : "approved" in value ? ContractStatus.approved : "executed" in value ? ContractStatus.executed : "draft" in value ? ContractStatus.draft : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: null;
} | {
    financing: null;
} | {
    license: null;
}): ContractType {
    return "custom" in value ? ContractType.custom : "financing" in value ? ContractType.financing : "license" in value ? ContractType.license : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MarketplaceListing;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: MarketplaceListing;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    revoked: null;
}): ApiKeyStatus {
    return "active" in value ? ApiKeyStatus.active : "revoked" in value ? ApiKeyStatus.revoked : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WebhookDeliveryLog;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WebhookDeliveryLog;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WebhookEndpoint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WebhookEndpoint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contract>): Array<Contract> {
    return value.map((x)=>from_candid_Contract_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiKey>): Array<ApiKey> {
    return value.map((x)=>from_candid_ApiKey_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContractTemplate>): Array<ContractTemplate> {
    return value.map((x)=>from_candid_ContractTemplate_n20(_uploadFile, _downloadFile, x));
}
function to_candid_ContractType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): _ContractType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): {
    custom: null;
} | {
    financing: null;
} | {
    license: null;
} {
    return value == ContractType.custom ? {
        custom: null
    } : value == ContractType.financing ? {
        financing: null
    } : value == ContractType.license ? {
        license: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
